name: restaurant_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  smooth_page_indicator: ^1.1.0
  expandable_text: ^2.3.0

  # flutter_stripe: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/OnBoarding/"
    - "assets/foodImages/"
